version: '3'
services:
    app:
        build:
            context: ${PWD}
            dockerfile: Dockerfile
        environment:
            - MYSQL_HOST
            - MYSQL_USER
            - MYSQL_PASSWORD
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html
        env_file:
            - .env.local
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 33060:3306